### ISSUE TITLE
T48

### ISSUE THREAD

**Issue by nbdy32** [mafe72/27c160-tl866-adapter#2]
HI, is it possible tu use this adapter with T48 programmer ??? (TL866-3G) ???

**Comment by L10N37** [comment]
They sell adapters for that on ali express. I was here to ask about MX29F1615 used in adapter as I threw this together on a breadboard, just opened it in kicad and traced out every connection. It worked fine multiple times on personal pulls out of a Naomi 1 and Naomi 2, but I just tried a batch of 30 (3 lots of 10, from eBay and ali express, all different sellers) and they all blank check fine after UV erase (well most of them), but then fail instantly in flashing. 

I want to use MX29F1615 instead.

Here is one for you:

https://www.aliexpress.com/item/1005004743064970.html

If dev see this, please let me know if this will work on the flash chip stated :)

**Comment by mafe72** [comment]
> HI, is it possible tu use this adapter with T48 programmer ??? (TL866-3G) ???

nbdy32,
I just got my TL866-3G from aliexpress and I can confirm this adapter works with the T48.

**Comment by mafe72** [comment]
> They sell adapters for that on ali express. I was here to ask about MX29F1615 used in adapter as I threw this together on a breadboard, just opened it in kicad and traced out every connection. It worked fine multiple times on personal pulls out of a Naomi 1 and Naomi 2, but I just tried a batch of 30 (3 lots of 10, from eBay and ali express, all different sellers) and they all blank check fine after UV erase (well most of them), but then fail instantly in flashing.
> 
> I want to use MX29F1615 instead.
> 
> Here is one for you:
> 
> https://www.aliexpress.com/item/1005004743064970.html
> 
> If dev see this, please let me know if this will work on the flash chip stated :)

L10N37,
This adapter will not work with the MX29F1615.

Chris Hooper have designed a programmer for this EEPROM, you can find his excellent writeup and instructions at http://eebugs.com/mx29f1615
The hardware and firmware for the programmer are available on his GitHub at https://github.com/cdhooper/mx29f1615_programmer/tree/main/

Good luck!

**Comment by mafe72** [comment]
Thanks for your interest in this adapter!

**Comment by L10N37** [comment]
Thanks! I have an STM discovery board in the cupboard but it's a recently released one. I'll check out its compatibility. 

Maybe a T56 is on the line up which is drop in for everything mentioned here. Around $290 AUD at the moment shipped from China... steep.
